exclude:
  - backend/node_modules
  - backend/package.json
  - backend/package-lock.json
  - backend/.env
  - backend/.git
  - backend/dist
  - README.md
baseurl: "/repo-name"
url: "https://mrdeveloper917.github.io"
